# Numpy

https://cs231n.github.io/python-numpy-tutorial/
about Python, numpy, scipy, matplotlib

기본 파이썬, 라이브러리 활용 경험이 없으신 분은 위 사이트의 코드를 반드시 연습하세요.
기초입니다. 


In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-1.03908297, -1.08344461, -1.18638158],
       [-0.68749823,  0.81679162, -0.934542  ]])

In [3]:
data * 10

array([[-10.39082965, -10.83444607, -11.8638158 ],
       [ -6.87498227,   8.16791621,  -9.34542002]])

In [4]:
data + data

array([[-2.07816593, -2.16688921, -2.37276316],
       [-1.37499645,  1.63358324, -1.869084  ]])

In [5]:
data.shape

(2, 3)

In [6]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [7]:
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [8]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [11]:
d = np.eye(5)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# array indexing

# slicing

In [12]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [14]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

2


In [15]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77


In [16]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [19]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


# integer array indexing

In [20]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [22]:
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [23]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# boolean indexing

In [24]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

[[False False]
 [ True  True]
 [ True  True]]


In [26]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

[3 4 5 6]


In [27]:
# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[3 4 5 6]


# pandas

https://www.kaggle.com/learn/pandas


In [28]:
import pandas as pd

In [29]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [30]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

# Read files

In [31]:
reviews = pd.read_csv("winemag-data-130k-v2.csv")

In [32]:
reviews.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [33]:
reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

In [34]:
reviews.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

# indexing

In [35]:
reviews.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [36]:
reviews['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [37]:
reviews['country'][0]
# reviews.loc[0, 'country']

'Italy'

index-based selection: selecting data based on its numerical position in the data

In [38]:
reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [39]:
reviews.iloc[:, 0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [40]:
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [41]:
reviews.iloc[-5:]

country                                        description  \
129966  Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967       US  Citation is given as much as a decade of bottl...   
129968   France  Well-drained gravel soil gives this wine its c...   
129969   France  A dry style of Pinot Gris, this is crisp with ...   
129970   France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price province  \
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0    Mosel   
129967                                     NaN      90   75.0   Oregon   
129968                                   Kritt      90   30.0   Alsace   
129969                                     NaN      90   32.0   Alsace   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   Alsace   

       region_1      region_2         taster_name taster_twitter_handle  \
129966      NaN           NaN  Anna Lee C. Iijima                   NaN   
129967   Oregon  Oregon Other        Paul Gregutt           @paulgwine    
129968   Alsace           NaN          Roger Voss            @vossroger   
129969   Alsace           NaN          Roger Voss            @vossroger   
129970   Alsace           NaN          Roger Voss            @vossroger   

                                                    title         variety  \
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                                          winery  
129966  Dr. H. Thanisch (Erben Müller-Burggraef)  
129967                                  Citation  
129968                           Domaine Gresser  
129969                      Domaine Marcel Deiss  
129970                          Domaine Schoffit

label-based selection use 'index'

In [42]:
reviews.loc[0, 'country']

'Italy'

In [43]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

# conditional selection

In [44]:
reviews.country == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...  
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [45]:
reviews.loc[reviews.country == 'Italy']

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
13       Italy  This is dominated by oak and oak-driven aromas...   
22       Italy  Delicate aromas recall white flower and citrus...   
24       Italy  Aromas of prune, blackcurrant, toast and oak c...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  \
0                    Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                         Belsito      87   16.0  Sicily & Sardinia   
13                          Rosso      87    NaN  Sicily & Sardinia   
22                      Ficiligno      87   19.0  Sicily & Sardinia   
24                          Aynat      87   35.0  Sicily & Sardinia   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              region_1 region_2    taster_name  \
0                                 Etna      NaN  Kerin O’Keefe   
6                             Vittoria      NaN  Kerin O’Keefe   
13                                Etna      NaN  Kerin O’Keefe   
22                             Sicilia      NaN  Kerin O’Keefe   
24                             Sicilia      NaN  Kerin O’Keefe   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       taster_twitter_handle  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title            variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...           Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...          Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...          Red Blend   
129961                        COS 2013 Frappato (Sicilia)           Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...       Nero d'Avola   

                                 winery  
0                               Nicosia  
6                       Terre di Giurfo  
13                  Masseria Setteporte  
22                

In [46]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

country                                        description  \
120      Italy  Slightly backward, particularly given the vint...   
130      Italy  At the first it was quite muted and subdued, b...   
133      Italy  Einaudi's wines have been improving lately, an...   
135      Italy  The color is just beginning to show signs of b...   
140      Italy  A big, fat, luscious wine with plenty of toast...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  \
120           Bricco Rocche Prapó      92   70.0           Piedmont   
130         Bricco Rocche Brunate      91   70.0           Piedmont   
133                           NaN      91   68.0           Piedmont   
135                        Sorano      91   60.0           Piedmont   
140                   Costa Bruna      90   26.0           Piedmont   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              region_1 region_2    taster_name  \
120                             Barolo      NaN            NaN   
130                             Barolo      NaN            NaN   
133                             Barolo      NaN            NaN   
135                             Barolo      NaN            NaN   
140                     Barbera d'Alba      NaN            NaN   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       taster_twitter_handle  \
120                      NaN   
130                      NaN   
133                      NaN   
135                      NaN   
140                      NaN   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title       variety  \
120            Ceretto 2003 Bricco Rocche Prapó  (Barolo)      Nebbiolo   
130          Ceretto 2003 Bricco Rocche Brunate  (Barolo)      Nebbiolo   
133                     Poderi Luigi Einaudi 2003  Barolo      Nebbiolo   
135                 Giacomo Ascheri 2001 Sorano  (Barolo)      Nebbiolo   
140       Poderi Colla 2005 Costa Bruna  (Barbera d'Alba)       Barbera   
...                                                   ...           ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...      Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...     Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...     Red Blend   
129961                        COS 2013 Frappato (Sicilia)      Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...  Nero d'Avola   

                                 winery  
120                             Ceretto  
130                             Ceretto  
133                Poderi Luigi Einaudi  
135                     Giacomo Ascheri  
140                        Poderi Co

# assigning data

In [47]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  index_backwards  
0     White Blend              Nicosia           129971  
1  Portuguese Red  Quinta dos Avidagos           129970  
2      Pinot Gris            Rainstorm           129969  
3        Riesling           St. Julian           129968  
4      Pinot Noir         Sweet Cheeks           129967

# summary function

In [48]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [49]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [50]:
reviews.taster_name.value_counts()

Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: taster_name, dtype: int64

# missing data

In [51]:
pd.isnull(reviews.country)

0         False
1         False
2         False
3         False
4         False
          ...  
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [52]:
reviews[pd.isnull(reviews.country)]

country                                        description  \
913        NaN  Amber in color, this wine has aromas of peach ...   
3131       NaN  Soft, fruity and juicy, this is a pleasant, si...   
4243       NaN  Violet-red in color, this semisweet wine has a...   
9509       NaN  This mouthwatering blend starts with a nose of...   
9750       NaN  This orange-style wine has a cloudy yellow-gol...   
...        ...                                                ...   
124176     NaN  This Swiss red blend is composed of four varie...   
129407     NaN  Dry spicy aromas of dusty plum and tomato add ...   
129408     NaN  El Capricho is one of Uruguay's more consisten...   
129590     NaN  A blend of 60% Syrah, 30% Cabernet Sauvignon a...   
129900     NaN  This wine offers a delightful bouquet of black...   

                           designation  points  price province region_1  \
913                     Asureti Valley      87   30.0      NaN      NaN   
3131                          Partager      83    NaN      NaN      NaN   
4243          Red Naturally Semi-Sweet      88   18.0      NaN      NaN   
9509    Theopetra Malagouzia-Assyrtiko      92   28.0      NaN      NaN   
9750         Orange Nikolaevo Vineyard      89   28.0      NaN      NaN   
...                                ...     ...    ...      ...      ...   
124176                    Les Romaines      90   30.0      NaN      NaN   
129407                         Reserve      89   22.0      NaN      NaN   
129408                         Reserve      89   22.0      NaN      NaN   
129590                            Shah      90   30.0      NaN      NaN   
129900                             NaN      91   32.0      NaN      NaN   

       region_2        taster_name taster_twitter_handle  \
913         NaN      Mike DeSimone        @worldwineguys   
3131        NaN         Roger Voss            @vossroger   
4243        NaN      Mike DeSimone        @worldwineguys   
9509        NaN    Susan Kostrzewa         @suskostrzewa   
9750        NaN       Jeff Jenssen        @worldwineguys   
...         ...                ...                   ...   
124176      NaN       Jeff Jenssen        @worldwineguys   
129407      NaN  Michael Schachner           @wineschach   
129408      NaN  Michael Schachner           @wineschach   
129590      NaN      Mike DeSimone        @worldwineguys   
129900      NaN      Mike DeSimone        @worldwineguys   

                                                    title             variety  \
913        Gotsa Family Wines 2014 Asureti Valley Chinuri             Chinuri   
3131                    Barton & Guestier NV Partager Red           Red Blend   
4243    Kakhetia Traditional Winemaking 2012 Red Natur...            Ojaleshi   
9509    Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...         White Blend   
9750    Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...          Chardonnay   
...                                                   ...                 ...   
124176            Les Frères Dutruy 2014 Les Romaines Red           Red Blend   
129407        El Capricho 2015 Reserve Cabernet Sauvignon  Cabernet Sauvignon   
129408               El Capricho 2015 Reserve Tempranillo         Tempranillo   
129590                            Büyülübağ 2012 Shah Red           Red Blend   
129900                                 Psagot 2014 Merlot              Merlot   

                                 winery  index_backwards  
913                  Gotsa Family Wines           129058  
3131                  Barton & Guestier           126840  
4243    Kakhetia Traditional Winemaking           125728  
9509                           Tsililis           120462  
9750                           Ross-idi           120221  
...                                 ...              ...  
124176                Les Frères Dutruy             5795  
129407                      El Capricho              564  
129408                      El Capricho             

In [53]:
reviews.region_2.fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...        
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [54]:
reviews

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer 

In [55]:
reviews.region_2.fillna("Unknown", inplace=True)

In [56]:
reviews

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna            Unknown   
1                   Douro                  NaN            Unknown   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore            Unknown   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN            Unknown   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace            Unknown   
129969             Alsace               Alsace            Unknown   
129970             Alsace               Alsace            Unknown   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer 

# combining (join)

In [57]:
data_A = {'key': [1,2,3], 'name': ['Jane', 'John', 'Peter']}
dataframe_A = pd.DataFrame(data_A, columns = ['key', 'name'])

data_B = {'key': [2,3,4], 'age': [18, 15, 20]}
dataframe_B = pd.DataFrame(data_B, columns = ['key', 'age'])

print(dataframe_A)
print(dataframe_B)

   key   name
0    1   Jane
1    2   John
2    3  Peter
   key  age
0    2   18
1    3   15
2    4   20


In [58]:
df_INNER_JOIN = pd.merge(dataframe_A, dataframe_B, left_on='key', right_on='key', how='inner')
print(df_INNER_JOIN)

   key   name  age
0    2   John   18
1    3  Peter   15


In [59]:
df_LEFT_JOIN = pd.merge(dataframe_A, dataframe_B, left_on='key', right_on='key', how='left')
print(df_LEFT_JOIN)

   key   name   age
0    1   Jane   NaN
1    2   John  18.0
2    3  Peter  15.0


In [60]:
df_RIGHT_JOIN = pd.merge(dataframe_A, dataframe_B, left_on='key', right_on='key', how='right')
print(df_RIGHT_JOIN)

   key   name  age
0    2   John   18
1    3  Peter   15
2    4    NaN   20


In [61]:
df_OUTER_JOIN = pd.merge(dataframe_A, dataframe_B, left_on='key', right_on='key', how='outer')
print(df_OUTER_JOIN)

   key   name   age
0    1   Jane   NaN
1    2   John  18.0
2    3  Peter  15.0
3    4    NaN  20.0
