In [18]:
# import nltk
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
# nltk.download('wordnet')
# nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [1]:
# Tokenization
# word tokenization -> 토큰의 기준을 단어(word)로 하는 경우

# 아포스트로피 처리
from nltk.tokenize import word_tokenize
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))
print()
from nltk.tokenize import WordPunctTokenizer
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))
print()
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))
print()
# 표준 토큰화 예제
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


In [2]:
# 문장 토큰화
from nltk.tokenize import sent_tokenize
text = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print(sent_tokenize(text))
print()
text_2 = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text_2))
print()

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']



In [3]:
# 품사 태깅
from nltk.tokenize import word_tokenize
text = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
from nltk.tag import pos_tag
tokenized_sentence = word_tokenize(text)
print(pos_tag(tokenized_sentence))

[('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


In [4]:
# 정제(cleaning) and 정규화(Normalization)
import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 얻어낸 코퍼스에서 노이즈 데이터의 특징을 잡아낼 수 있다면 정규 표현식을 통해서 이를 제거 (HTML 태그, 기사의 게재 시간 등의 규칙 기반)
shortword = re.compile(r'\W*\b\w{1,2}\b') # 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
print(shortword.sub('', text))

 was wondering anyone out there could enlighten this car.


In [5]:
# 어간 추출(Stemming) and 표제어 추출(Lemmatiztion)
## 표제어: 문법적 의미가 같은 것 -> 형태학적 파싱 진행(형태소 단위부터 시작하여 단어를 만들어 감)
## 형태소 - 어간(stem): 단어의 의미를 담고 있는 단어의 핵심 부분, 접사(affix): 단어에 추가적인 의미를 주는 부분

#표제어 추출
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
lemmatize_word = []
for w in words:
    lemmatize_word.append(lemmatizer.lemmatize(w))
print(lemmatize_word)

# 정확하지 않은 단어는 품사의 정보를 입력해주어야 함.
lemmatizer.lemmatize('dies', 'v')
lemmatizer.lemmatize('watched', 'v')
lemmatizer.lemmatize('has', 'v')

['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


'have'

In [6]:
# 어간 추출
## Porterstemmer 알고리즘
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer = PorterStemmer()
text = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
words = word_tokenize(text)
print(words)
print()
print([stemmer.stem(w) for w in words])
print()
## Lancasterstemmer 알고리즘
from nltk.stem import LancasterStemmer
lancaster_stemmer = LancasterStemmer()
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([stemmer.stem(w) for w in words])
print([lancaster_stemmer.stem(w) for w in words])

['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']

['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


In [7]:
# 불용어(stopword)

from nltk.corpus import stopwords
stopwords.words('english')[:10]

# NLTK 통해서 불용어 제거
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []
for w in word_tokens:
    if w not in stop_words:
        result.append(w)
print(word_tokens)
print(result)

['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [8]:
# 정규표현식 -> re 모듈 활용
import re

# .기호 -> 한 개의 임의의 문자를 뜻함
r = re.compile("a.c")
r.search("kkk")
r.search("abc")

# ?기호 -> ? 앞의 문자가 존재할 수도 있고, 존재하지 않을 수도 있는 경우를 나타냄
r = re.compile("ab?c")
r.search("abbc")
r.search("abc")
r.search("ac")

# *기호 -> 바로 앞의 문자가 0개 이상일 경우. 앞의 문자는 존재하지 않을 수도 있고 여러 개일 수도 있음
r = re.compile("ab*c")
r.search("a")
r.search("ac")
r.search("abc")
r.search("abbbbc")

# +기호 -> *과 유사하나 앞의 문자가 최소 1개 이상이어야함
r = re.compile("ab+c")
r.search("ac")
r.search("abc")
r.search("abbbbc")

# ^기호 -> 시작되는 글자를 지정
r = re.compile("^a")
r.search("bbc")
r.search("ab")

# {숫자}기호 -> 해당 문자를 숫자만큼 반복한 것
r = re.compile("ab{2}c")
r.search("ac")
r.search("abc")
r.search("abbc")
r.search("abbbbc")

# {숫자1, 숫자2}기호 -> 해당 문자를 숫자1 이상 숫자2이하만큼 반복
r = re.compile("ab{2,8}c")
r.search("ac")
r.search("abc")
r.search("abbbc")

# {숫자,}기호 -> 해당 문자를 숫자 이상 만큼 반복
r = re.compile("a{2,}bc")
r.search("bc")
r.search("aa")
r.search("aabc")
r.search("aaaaaaaabc")

# []기호 -> 대괄호안 문자들 중 한개의 문자와 매치
r = re.compile("[abc]")
r.search("zzz")
r.search("a")
r.search("aaaaa")
r.search("baaac")

# [^문자]기호 -> ^ 기호 뒤에 붙은 문자들을 제외한 모든 문자를 매치
r = re.compile("[^abc]")
r.search("a")
r.search("ab")
r.search("1")

# re.split() -> 문자열을 분리하여 리스트로 리턴화
text = "사과 딸기 수박 메론 바나나"
re.split(" ", text)

text ="""사과
딸기
수박
메론
바나나"""
re.split("\n", text)

text = "사과+딸기+수박+메론+바나나"
re.split("\+", text)

# re.findall() -> 정규 표현식과 매치되는 모든 문자열들을 리스트로 리턴
text = """이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 : 남"""
re.findall("\d+", text)

# re.sub() -> 정규 표현식 패턴과 일치하는 문자열을 찾아 다른 문자열로 대체
text = "Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."
re.sub('[^a-zA-Z]',' ',text)

'Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern '

In [9]:
# 정규 표현식 텍스트 전처리 예제
text = """100 John    PROF
101 James   STUD
102 Mac   STUD"""

re.split('\s+', text)
re.findall('\d+', text)
re.findall('[A-Z]', text)
re.findall('[A-Z][a-z]+', text)

['John', 'James', 'Mac']

In [10]:
# 정규 표현식 이용 토큰화
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer("[\w]+")
print(tokenizer.tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"))

tokenizer = RegexpTokenizer("\s+", gaps=True)
print(tokenizer.tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"))

['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [11]:
# 정수 인코딩 풀이
# dictionary
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

sentences = sent_tokenize(raw_text)
print(sentences)
print()
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []
    
    for word in tokenized_sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2:
                
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0
                vocab[word] += 1
    preprocessed_sentences.append(result)
print(preprocessed_sentences)
print()
print(vocab)

vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)
print()

word_to_index = {} # 빈도수가 높은 단어일수록 낮은 정수 인덱스를 부여
i = 0
for (word, frequency) in vocab_sorted:
    if frequency > 1:
        i = i + 1
        word_to_index[word] = i
        
print(word_to_index)
print()

# 상위 n개의 단어만 사용
vocab_size = 5
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size + 1]
for w in words_frequency:
    del word_to_index[w]
print(word_to_index)
print()

# Out-Of-Vocabulary
word_to_index['OOV'] = len(word_to_index) + 1
print(word_to_index)
print()

# encoding
encoded_sentences = []
for sentence in preprocessed_sentences:
    encoded_sentence = []
    for word in sentence:
        try:
            encoded_sentence.append(word_to_index[word])
        except KeyError:
            encoded_sentence.append(word_to_index['OOV'])
    encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}
[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good'

In [12]:
# Counter 사용 encoding
from collections import Counter
print(preprocessed_sentences)
print()

# 겹대괄호 제거 -> np.hstack(preprocessed_sentences)로도 가능
all_words_list = sum(preprocessed_sentences, [])
print(all_words_list)
print()

vocab = Counter(all_words_list)
print(vocab)
print()

vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

word_to_index = {}
i = 0
for (word, frequency) in vocab:
    i += 1
    word_to_index[word] = i

print(word_to_index)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 

In [13]:
# NLTK FreqDist -> 빈도수 계산 도구 사용 encoding
from nltk import FreqDist
import numpy as np

vocab = FreqDist(np.hstack(preprocessed_sentences))
print(vocab["barber"])
print()

vocab_size = 5
vocab = vocab.most_common(vocab_size)
print(vocab)
print()

word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}
print(word_to_index)

8

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [14]:
# text preprocessing by keras

from tensorflow.keras.preprocessing.text import Tokenizer
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

tokenizer = Tokenizer()

# fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성
tokenizer.fit_on_texts(preprocessed_sentences)
print(tokenizer.word_index) # 인덱스 부여 dict
print(tokenizer.word_counts) # 빈도수 ordereddict
print(tokenizer.texts_to_sequences(preprocessed_sentences)) # 입력으로 들어온 corpus에 대해서 각 단어를 이미 정해진 인덱스로 변환, []: 문장 단위, [[]] : 단어 단위
print()

vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 1)
tokenizer.fit_on_texts(preprocessed_sentences)
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentences))
print()

# keras에서는 OOV에 대해서 단어를 아예 제거해버림. 보존하고싶다면 oov_token 활용, keras OOV 인덱스는 1로 설정
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token = 'OOV')
tokenizer.fit_on_texts(preprocessed_sentences)
print('단어 OOV의 인덱스 : {}'.format(tokenizer.word_index['OOV']))
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]

단어 OOV의 인덱스 : 1
[[2, 6], [2, 1, 

In [15]:
# Padding -> 병렬 연산을 위해서 여러 문장의 길이를 임의로 동일하게 맞춰주는 작업

# numpy padding
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

tokenizer = Tokenizer()

# fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합 생성
tokenizer.fit_on_texts(preprocessed_sentences)

encoded  = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)
print()

max_len = max(len(item) for item in encoded)
print(max_len)
print()

for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)

padded_np = np.array(encoded)
print(padded_np) # zero padding -> 0는 아무런 의미도 없어 자연어 처리시 무시됨.

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]

7

[[ 1  5  0  0  0  0  0]
 [ 1  8  5  0  0  0  0]
 [ 1  3  5  0  0  0  0]
 [ 9  2  0  0  0  0  0]
 [ 2  4  3  2  0  0  0]
 [ 3  2  0  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  2  0  0  0  0]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13  0  0  0]]


In [16]:
# keras padding

from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)
print()
padded = pad_sequences(encoded, padding = 'post') # padding ='post' 인자로 zero padding
print(padded)
print()

print((padded == padded_np).all())
print()

# max 값 제한 가능
padded = pad_sequences(encoded, padding = 'post', maxlen = 5)
print(padded)

# 0이 아닌 다른 수로 패딩
last_value = len(tokenizer.word_index) + 1 # 단어 집합의 크기보다 1 큰 숫자를 사용
print(last_value)
padded = pad_sequences(encoded, padding = 'post', value = last_value)
print(padded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]

[[ 1  5  0  0  0  0  0]
 [ 1  8  5  0  0  0  0]
 [ 1  3  5  0  0  0  0]
 [ 9  2  0  0  0  0  0]
 [ 2  4  3  2  0  0  0]
 [ 3  2  0  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  2  0  0  0  0]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13  0  0  0]]

True

[[ 1  5  0  0  0]
 [ 1  8  5  0  0]
 [ 1  3  5  0  0]
 [ 9  2  0  0  0]
 [ 2  4  3  2  0]
 [ 3  2  0  0  0]
 [ 1  4  6  0  0]
 [ 1  4  6  0  0]
 [ 1  4  2  0  0]
 [ 3  2 10  1 11]
 [ 1 12  3 13  0]]
14
[[ 1  5 14 14 14 14 14]
 [ 1  8  5 14 14 14 14]
 [ 1  3  5 14 14 14 14]
 [ 9  2 14 14 14 14 14]
 [ 2  4  3  2 14 14 14]
 [ 3  2 14 14 14 14 14]
 [ 1  4  6 14 14 14 14]
 [ 1  4  6 14 14 14 14]
 [ 1  4  2 14 14 14 14]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13 14 14 14]]


In [17]:
# One-Hot Encoding: 단어 집합의 크기를 벡터의 차원으로 하고, 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 다른 인덱스에는 0을 부여하는 단어의 벡터 표현 방식. -> One-Hot vector
# 과정 -> 1) 각 단어에 고유한 인덱스를 부여 (정수 인코딩), 2) 표현하고 싶은 단어의 인덱스 위치에 1을 부여하고, 다른 단어의 인덱스 위치에는 0을 부여
# 단어 집합(vocabulary): 단어의 변형 형태도 다른 단어로 간주하여 중복을 허용하지 않고 모아놓은 집합

# keras one-hot encoding

## vocab 구성
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = sent_tokenize(text)
stop_words = set(stopwords.words('english'))

preprocessed_sentences = []

for sentence in sentences: # 불용어 처리 및 의미있는 어간 추출
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []
    
    for word in tokenized_sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2:
                result.append(word)
    preprocessed_sentences.append(result)
    
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(tokenizer.word_index)

# sub_text에 one-hot encoding
sub_text = "a barber is huge person. he Knew A Secret!"

encoded_sub = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded_sub)

one_hot = to_categorical(encoded_sub)
print()
print(one_hot)

# one-hot encoding은 단어의 개수가 늘어날 수록, 벡터를 저장하기 위해 필요한 공간이 늘어난다는 단점이 있음. 즉 단어 집합의 크기가 곧 벡터의 차원 수가 됨.
# 또한 단어의 유사도를 표현하지 못함 -> 1) LSA, HAL 2) NNLM, RNLM, Word2Vec, FastText 3) GloVe 로 해결

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
[1, 3, 5, 9, 2]

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
# 데이터의 분리 -> train, test data set

# 사이킷 런을 이용하여 분리
import numpy as np
from sklearn.model_selection import train_test_split

X, y =np.arange(10).reshape((5, 2)), range(5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state=1234) # test_size: 비율, random_state: 난수 시드

print(X_train)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
