In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import requests

In [2]:
# use matrix with numpy
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5 , 6]
])

B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

C = np.random.rand(3, 5)

print(A)
print()
print(B)
print()
print(C)
print()
print(np.zeros((2, 4)))

[[ 1 -1  2]
 [ 3  2  2]
 [ 4  1  2]
 [ 7  5  6]]

[[ 0  1]
 [-1  3]
 [ 5  2]]

[[0.10932609 0.84808028 0.31461369 0.74041717 0.70219479]
 [0.29710548 0.72305728 0.51516441 0.43767583 0.56187727]
 [0.91278161 0.62870426 0.11213023 0.98038717 0.47800591]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
print(A[0][2])

2


In [4]:
# 실습과제_numpy 행렬 연습

A_list = [[0, 1, -1], [1, 2, 3], [2, 1, 0], [-1, 2, -4]]
A = np.array(A_list)

B_list = [[0, 2], [1, 1], [-1, -2]]
B = np.array(B_list)

print(A)
print(B)
print(A[1][1])
print(A[3][0])


# vector -> 차원이 1인 행렬

[[ 0  1 -1]
 [ 1  2  3]
 [ 2  1  0]
 [-1  2 -4]]
[[ 0  2]
 [ 1  1]
 [-1 -2]]
2
-1


# calculate matrix
행렬 연산은 차원이 같아야한다.
덧셈: 같은 원소끼리 더함, 스칼라 곱: 스칼라를 주어진 matrix의 각 원소에 곱해주면 된다.

두 행렬의 내적곱: 2*3인 A행렬, 3*2인 B행렬을 정의했을 때 A(*)B는 2*2인 행렬이 나온다.(A에서 row 갯수, B에서 column 갯수)  
단, A의 열 갯수 = B의 행 갯수여야 행렬 간의 곱셈이 가능하다.  
즉, m*n인 A행렬과 n*p인 B행렬이 있을 경우, n으로 동일하기 때문에 AB는 m*p인 행렬이 만들어진다.  
또한 AB와 BA는 다른 식이다.(순서를 구분, 교환법칙 성립x)  
각 원소에는 A의 행과 B의 열의 각 원소를 순서대로 서로 곱해주고 차례대로 더해서 집어넣어 하나의 원소를 만든다.  

요소별 곱: 두 행렬의 차원이 같을 경우, 각 원소끼리 곱하여 새로운 행렬을 만듦(A∘B)  
내적곱을 하면 차원이 사라지기 때문에 요소별 곱을 사용하는 경우가 있다.

In [5]:
# numpy로 요소별 곱하기
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

print(A*B) # 행렬 요소간의 곱은 *연산자

[[ 0  2  6]
 [ 8  0  6]
 [ 7 16  0]]


In [6]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

print(A+B) # 요소별 덧셈
print(5*A) # 요소별 스칼라 곱
print()
print(np.dot(A,B)) # 내적곱(행렬곱)
print(A@B)


[[ 1.72591366 -0.56431713  2.33761013]
 [ 3.62201235  2.95446095  2.37932861]
 [ 4.70749483  1.80941099  2.00061328]]
[[ 5 -5 10]
 [15 10 10]
 [20  5 10]]

[[ 1.51889098  1.1000439  -0.04049191]
 [ 4.83675535  4.83479249  1.77271418]
 [ 4.94065666  4.31601441  1.7309957 ]]
[[ 1.51889098  1.1000439  -0.04049191]
 [ 4.83675535  4.83479249  1.77271418]
 [ 4.94065666  4.31601441  1.7309957 ]]


In [7]:
# 실습과제_numpy로 행렬 연산 연습하기

import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])
# 2A X -B X (3C + D)
# 행렬 연산 결과를 result에 저장하세요
result = (2*A) @ ((-1) * B) @ (3*C + D)

result


array([[  34,  -28],
       [ 110, -130]])

In [9]:
# 전치, 단위 역행렬 사용
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

# 전치 행렬
A_transpose = np.transpose(A) # or A_transpose = A.T
print(A_transpose)
print()

# 단위 행렬
I = np.identity(3)
print(I)
# 단위 행렬 검증
print(A @ I)

print()
# 역 행렬
A_inverse = np.linalg.pinv(A)
print(A_inverse)
# 역 행렬 검증
print(A@A_inverse)

[[ 1  3  4]
 [-1  2  1]
 [ 2  2  2]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1. -1.  2.]
 [ 3.  2.  2.]
 [ 4.  1.  2.]]

[[-0.2 -0.4  0.6]
 [-0.2  0.6 -0.4]
 [ 0.5  0.5 -0.5]]
[[ 1.00000000e+00  5.55111512e-16 -8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 2.22044605e-16  2.22044605e-16  1.00000000e+00]]


In [12]:
# 실습과제_numpy로 전치, 단위, 역행렬 연습
import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

C_inverse = np.linalg.pinv(C)

# 행렬 연산을 result 변수에 저장하세요
result = (B.T) @ (2*A.T) @ (3*C_inverse + D.T)

print(result)

[[20. 98.]
 [56. 60.]]
